[functions]
  directory = "."  # This tells Netlify to look for functions in the root directory
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/send-email"
  to = "/server.js"
  status = 200
